# Generated by Django 4.1.7 on 2023-03-07 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktype',
            name='task',
        ),
        migrations.RemoveField(
            model_name='tasktype',
            name='type',
        ),
        migrations.DeleteModel(
            name='TaskStatus',
        ),
        migrations.DeleteModel(
            name='TaskType',
        ),
    ]
