# Generated by Django 4.1.7 on 2023-03-07 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_status_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.ManyToManyField(blank=True, related_name='type_tasks', to='webapp.type'),
        ),
    ]
