# Generated by Django 4.1.7 on 2023-03-07 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_alter_task_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='webapp.status'),
        ),
    ]
